/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimHistoryRouteImport } from './routes/sim-history'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetIdRouteImport } from './routes/asset.$id'

const SimHistoryRoute = SimHistoryRouteImport.update({
  id: '/sim-history',
  path: '/sim-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/inbox': typeof InboxRoute
  '/portfolio': typeof PortfolioRoute
  '/sim-history': typeof SimHistoryRoute
  '/asset/$id': typeof AssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/inbox': typeof InboxRoute
  '/portfolio': typeof PortfolioRoute
  '/sim-history': typeof SimHistoryRoute
  '/asset/$id': typeof AssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/inbox': typeof InboxRoute
  '/portfolio': typeof PortfolioRoute
  '/sim-history': typeof SimHistoryRoute
  '/asset/$id': typeof AssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/inbox'
    | '/portfolio'
    | '/sim-history'
    | '/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/inbox'
    | '/portfolio'
    | '/sim-history'
    | '/asset/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/inbox'
    | '/portfolio'
    | '/sim-history'
    | '/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  InboxRoute: typeof InboxRoute
  PortfolioRoute: typeof PortfolioRoute
  SimHistoryRoute: typeof SimHistoryRoute
  AssetIdRoute: typeof AssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sim-history': {
      id: '/sim-history'
      path: '/sim-history'
      fullPath: '/sim-history'
      preLoaderRoute: typeof SimHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  InboxRoute: InboxRoute,
  PortfolioRoute: PortfolioRoute,
  SimHistoryRoute: SimHistoryRoute,
  AssetIdRoute: AssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
